### PR TITLE
General improvements to the effect.

### PR DESCRIPTION
**Pull request by wolfbeast**
I've made some general improvements here:

- Slightly faster rain speed
- Less-than-straight-green because honestly, monitors don't do that :)
- Start with black
- Start with a cascade instead of a screen sweep.

### CODE REVIEW

**Comment by magician11** [comment]
hey!

Looks better for sure. I like how the lines starts at different times at the beginning.

I notice a slight delay as it starts when I first load it. Refreshing after that looks fine. Kinda weird. You see that?

And nice attention grabber with "Knock, Knock.."

**Comment by wolfbeast** [comment]
The slight delay would be because there's no guarantee that there will be a character position waiting right at the edge (it's random at -4000 to 0) so it may start immediately or there may be a small delay if there's just blanks close to the edge initially.

**Comment by magician11** [comment]
What I meant to say is that the CPU seems to max out.. and so it jumps a little. Once, loaded though it seems to work great.

screen shot 2017-09-25 at 10 58 06 pm

I'm thinking there is probably some loop that is processing a lot on load?

**Comment by wolfbeast** [comment]
Hmm, I don't see any of that happening on my system.
It might be because of drawing characters off-screen causing the drawing surface to extend beyond the visible canvas. I'm guessing if you don't have hardware acceleration that that might cause a lot more overhead. Easy fix though, if that's the case.

Let me know if it helps ;)

**Comment by magician11** [comment]
Mmm... I'm still getting a slight CPU jump at times and the lines stuttering a little when rendering. But I'm not sure exactly why.

I'll merge your pull request though because I do like your overall contributions. Great job. Especially with the cascade. Been meaning to do that.

**Comment by wolfbeast** [comment]
> Mmm... I'm still getting a slight CPU jump at times and the lines stuttering a little when rendering. But I'm not sure exactly why.

That may just be a general occurrence of GC in whatever JS engine your browser uses.

**Pull request merged**
